# Nombre del servicio
spring.application.name=usuarios-servicio

# Puerto del servicio
server.port=8081

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/usuarios_db

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT
jwt.secret=miClaveSecretaSuperSeguraDeAlMenos256BitsParaHMACSHA
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Servicio de gestión de usuarios
info.app.version=1.0.0

spring.config.import=optional:configserver:http://config-server:8888