spring.application.name=eureka-server
server.port=8761

# Evitar que el servidor se registre a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración de Eureka
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enableSelfPreservation=false

# Información de la aplicación
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Servidor de descubrimiento Eureka
info.app.version=1.0.0